project_id = "ynkqczsmcnxvapljofel"

[functions.lyrics-search]
verify_jwt = false

[functions.github-repo]
verify_jwt = false

[functions.code-scan]
verify_jwt = false

[functions.code-refactor]
verify_jwt = false
